### ISSUE TITLE
Tool installation issue on ARM based New Macbook

### ISSUE THREAD

**Issue by jayjpatel9717** [six2dez/reconftw#512]
**Description:**
=====
All of the tools, with the exception of `nrich` and `ppfuzz` are successfully installed. Both of the tools return an error. Is there a method to fix this situation?
<img width="891" alt="Screenshot 2022-04-30 at 11 12 31 AM" src="https://user-images.githubusercontent.com/20674409/166093258-9d5d3e2f-c4fc-48de-b4a1-772a1b778868.png">
<img width="910" alt="Screenshot 2022-04-30 at 11 13 09 AM" src="https://user-images.githubusercontent.com/20674409/166093260-acbe2329-ae91-4ffe-a776-1e22deee0279.png">
<img width="1376" alt="Screenshot 2022-04-30 at 11 13 33 AM" src="https://user-images.githubusercontent.com/20674409/166093262-4e5b1302-c1ed-413b-998c-8b171b4e3cb1.png">

**Comment by six2dez** [comment]
Seems to be something specific of Rust tools on ARM, I think I can't help here, maybe opening an issue on the respective repositories? @dwisiswant0 could you help here?

**Comment by Teicu** [comment]
There are only these two left that I can't install unfortunately  

 Checking installed tools 

 [*] interlace		[NO]
 [*] nrich		        [NO]

**Comment by six2dez** [comment]
Fixed on dev branch https://github.com/six2dez/reconftw/commit/944061fb9ec520241db09b114da93805d07e0f20 please check again

**Comment by Teicu** [comment]
Hi mate, 

Thanks for your interest and hard work, but I get exactly the same message. I deleted the old version and installed the latest one, but it seems useless   

 main-v2.3  

<img width="801" alt="Screenshot 2022-06-02 at 14 45 07" src="https://user-images.githubusercontent.com/1572822/171622402-099822b0-b198-445b-877b-2edec3ff5337.png">

**Comment by six2dez** [comment]
As I said, it's fixed on dev branch, so you need to switch to dev branch first :)

**Comment by Teicu** [comment]
I know and I did 

root@Pentest reconftw % git branch
* dev
  main
root@Pentest reconftw % git checkout dev
Already on 'dev'
Your branch is up to date with 'origin/dev'.


<img width="801" alt="Screenshot 2022-06-02 at 14 45 07" src="https://user-images.githubusercontent.com/1572822/171627408-dfcf5cdf-7323-4cb2-a6f0-781c97a055cc.png">


Anyway, thank you very much for kindly replying. I think I'll give up

**Comment by jayjpatel9717** [comment]
@six2dez Is there any fix for `ppfuzz` installation?

**Comment by six2dez** [comment]
If you reinstall from dev branch it should be fixed now :)

**Comment by jayjpatel9717** [comment]
@six2dez I have done that, Still getting error.
<img width="1512" alt="Screenshot 2022-06-04 at 3 11 02 PM" src="https://user-images.githubusercontent.com/20674409/171993871-712410fd-5918-4bab-b35e-d29b8cd5d62d.png">

<img width="1512" alt="Screenshot 2022-06-04 at 3 11 27 PM" src="https://user-images.githubusercontent.com/20674409/171993877-af7275b7-6c3c-4b2d-9e3a-802100d3f9d6.png">

**Comment by six2dez** [comment]
Ok, let me check during the day

**Comment by jayjpatel9717** [comment]
No problem, take your time, and thank you for your prompt response :)
