### ISSUE TITLE
Issue While running the Web Server 

### ISSUE THREAD

**Issue by Nittonull** [six2dez/reconftw#681]
Hi,

I am facing issue while starting the web server could you please let me know what is the issue and how to resolve

Error Description:

Starting web server... 
./reconftw.sh: line 2831: .venv/bin/activate: No such file or directory
 Web server started! 

After i open the link it is not running,

If i am doing anything wrong please help me out. :)

**Comment by six2dez** [comment]
It should be fixed by now, could you update and reinstall please? Thanks!

**Comment by shacrony** [comment]
I'm going through the same, I already installed it again but it's giving the same message "Starting web server...
./reconftw.sh: line 2830: .venv/bin/activate: No such file or directory
Web server started!"

**Comment by Nittonull** [comment]
Error Description: 

 Starting web server... 
reconftw.sh: line 2830: .venv/bin/activate: No such file or directory
 Web server started! 

Still It is there @six2dez mate!

**Comment by davidfegyver** [comment]
Hey, If i revert this change, actually the code works for me :D 

![image](https://user-images.githubusercontent.com/56135029/234395002-4dd10f60-aa56-45bc-b7ac-2ea988c6ae4d.png)

**Comment by six2dez** [comment]
I pushed a few changes and worked fine for me from zero (Ubuntu 22 updated), let me know if they works for you guys. I noticed some errors on Ubuntu 20 :/ we're on it! Let me know if this fix some of your scenarios. In order to test these changes, if you already have reconftw installed, just run the installer and pick the option number 3 @davidfegyver @Nittonull @shacrony Thanks!

**Comment by haxormad** [comment]
I am on Ubuntu 22.04.2 LTS x86_64 and it seems like the webserver is still broken. After starting the webserver, I do not see anything on port 8001, it is not listening on the port. Also cannot connect to the port. @six2dez

**Comment by six2dez** [comment]
Remember that the web interface requires python3.10 or greater, I've just added a check for this

**Comment by six2dez** [comment]
If you want to try to find the issue, this will be the steps to install and start the web interface manually, let me know where you spot the issue:

1. To install:

```bash
sudo rm -rf /web/.venv/
sudo pip3 install virtualenv
sudo virtualenv web/.venv/
sudo source web/.venv/bin/activate
sudo pip3 install --upgrade pip
sudo pip3 install -r web/requirements.txt
sudo apt install redis-server -y

sudo rm web/db.sqlite3
sudo python3 web/manage.py makemigrations &>/dev/null
sudo python3 web/manage.py migrate &>/dev/null
sudo python3 web/manage.py createsuperuser
```

2. To start it, from reconftw folder again:

```bash
ipAddress=$(hostname -I | cut -d ' ' -f1 | sed -e 's/ //')
cd web
sudo source web/.venv/bin/activate
sudo screen -S ReconftwWebserver -X kill
sudo screen -dmS ReconftwWebserver python3 manage.py runserver $ipAddress:8001
sudo service redis-server start
sudo screen -S ReconftwCelery -X kill
sudo screen -dmS ReconftwCelery python3 -m celery -A web worker -l info -P prefork -Q run_scans,default

```

After these steps the web server should be running on port 8001

**Comment by Nittonull** [comment]
@six2dez Thanks a lot it is working mate. :D have some errors after doing the login i will check i am able to resolve if not i will let you know. thanks a lot for efforts in fixing it mate.

**Comment by six2dez** [comment]
If you're not able to login, maybe reinstalling it to set up again the user and password could works!

**Comment by anubi5egypt** [comment]
> If you're not able to login, maybe reinstalling it to set up again the user and password could works!

start server still error can test it on Parrot Security os

**Comment by NadgobKhan** [comment]
Hello, the issue for me is that the directory /reconftw/web/.venv/bin/activate doesn't exists at all. I will try the fix @six2dez mentioned above and see if it works. Also, huge thank you for all your efforts brother (also for every contributor)!

**Comment by anubi5egypt** [comment]
i try with this fix step but the same problem 
![2023-04-29_13-01](https://user-images.githubusercontent.com/42506882/235309517-f1f3c67e-ccd9-4b0b-85a7-c6f9d6576b21.png)

**Comment by davidfegyver** [comment]
Hey, @anubi5egypt

In my opinion this is not a problem with reconftw, but your system. Is the port 8001 open on your local network? What happens if you try to reach the port through localhost? https://localhost:8001

**Comment by anubi5egypt** [comment]
![2023-04-29_16-24](https://user-images.githubusercontent.com/42506882/235332591-358d9cd1-c71d-43ca-8bfc-da061f258e46.png)

**Comment by anubi5egypt** [comment]
> Hey, @anubi5egypt
> 
> In my opinion this is not a problem with reconftw, but your system. Is the port 8001 open to your local network? What happens if you try to reach the port through localhost? http://localhost:8001

there is no the same problem

**Comment by anubi5egypt** [comment]
@six2dez can try plz to test on parrot security os

**Comment by david-botelho-mariano** [comment]
Same problem here, using fresh install of ubuntu 20.04 and latest reconftw (README.md)

**Comment by AnonymousWP** [comment]
From what I can find, the webinterface only works for installing reconFTW on the host? I'd like to install it in a container, but the Dockerfile has not been updated and there's no Docker Compose file either.

**Comment by jr69ss** [comment]
I was able to get the web interface working as expected after using the manual fix steps to create the virtualenv. However, when I try to run a scan, nothing happens. I cannot find any useful logs anywhere that state what is happening/failing, and there is not indication that anything is wrong.

**Comment by jakre1234** [comment]
Web Server won't run, the command says server started but in actual can't connect to the specified address

**Comment by six2dez** [comment]
We have deployed more fixes today, can any of you try to install from zero? Otherwise I will try to do it during the week

**Comment by jakre1234** [comment]
Tried 10 minutes before making the last comment, not working on my side.

**Comment by anubi5egypt** [comment]
> We have deployed more fixes today, can any of you try to install from zero? Otherwise I will try to do it during the week

yes i see it's worked , when i start recon domin there is no respon on web interface

**Comment by ZSC0810** [comment]
-bash: web/.venv/bin/activate: No such file or directory


root@ReconFTW:~/reconftw# ipAddress=$(hostname -I | cut -d ' ' -f1 | sed -e 's/ //')
root@ReconFTW:~/reconftw# cd web
root@ReconFTW:~/reconftw/web# source web/.venv/bin/activate
-bash: web/.venv/bin/activate: No such file or directory
root@ReconFTW:~/reconftw/web# python3 -V
Python 3.10.6
root@ReconFTW:~/reconftw/web# uname -a
Linux ReconFTW 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by six2dez** [comment]
Hey! Could you try to install it from dev branch?

**Comment by ZSC0810** [comment]
i install it  
git clone https://github.com/six2dez/reconftw
cd reconftw/
./install.sh
./reconftw.sh -d target.com -r

how to install it from dev branch?

**Comment by AnonymousWP** [comment]
> i install it git clone https://github.com/six2dez/reconftw cd reconftw/ ./install.sh ./reconftw.sh -d target.com -r
> 
> how to install it from dev branch?

Try:

```
git clone -b dev https://github.com/six2dez/reconftw
cd reconftw/
./install.sh
./reconftw.sh -d target.com -r
```

**Comment by ZSC0810** [comment]
I have been trying for a whole day, and it always fails to open the web service

**Comment by AnonymousWP** [comment]
> I have been trying for a whole day, and it always fails to open the web service

So does that mean you tried what I suggested and it still gives you the same error as you posted earlier?

**Comment by ZSC0810** [comment]
ok i will try now

**Comment by ZSC0810** [comment]
That's cool, too excited，I can access the WEB successfully, thank you so much

**Comment by m0pam** [comment]
I just installed from scratch on a fresh Ubuntu 22.04, it didn't matter I keep getting the same error `./install.sh: line 257: web/.venv/bin/activate: No such file or directory` ...

**Comment by six2dez** [comment]
Web interface will be removed on next release
