### ISSUE TITLE
 metafinder command failed

### ISSUE THREAD

**Issue by dgraghav** [six2dez/reconftw#790]
Scanning metadata in public files                                                                                                                                
metafinder command failed
how to solve it?

**Comment by GraylockInc** [comment]
# the lines out in reconftw.sh
![image](https://github.com/six2dez/reconftw/assets/70162517/038a4e20-15c6-40f4-aff2-82c6845c8155)

**Comment by GraylockInc** [comment]
Sorry it chopped part of my response, search for the metafinder lines in reconftw.sh and # them out as showed.

**Comment by earth92** [comment]
Installing metafinder, Manually solved it for me. Install below package.

https://github.com/Josue87/MetaFinder

**Comment by six2dez** [comment]
Fixed metafinder requirements to not get issues on it's installation

**Comment by jakre1234** [comment]
This is still a problem, tried 3 times and it's always metafinder which fails. Running metafinder manually works fine tho :/
